### ISSUE TITLE
[GR1 VOTING] Baseline Plugins (Excel & Oracle)

### ISSUE THREAD

**Issue by Souptacular** [eea-oasis/baseline-grants#12]
## Grant name
**[GR1] - Baseline Plugins (Excel & Oracle)**

## Applicant
Biswashree Dey (@biscuitdey)

## Grant Link
[Click Here](https://github.com/ethereum-oasis/baseline-grants/issues/4)

-------------------------------------------------------------------

Committee members: Please vote :thumbsup: if you want to vote to approve this grant or :thumbsdown: if you want to vote to not approve the grant. You vote via the smiley face icon on the top right portion of this text box.

![image](https://user-images.githubusercontent.com/3460120/110418245-cecfbf00-805c-11eb-87ba-5a47b7ecb4eb.png)

**NOTE: Only committee member can vote.**

**Comment by humbitious** [comment]
Oracle Flexcube...interesting!
Note that there is some work on the Excel plugin from the hackathon that ran over the winter holidays.

**Comment by humbitious** [comment]
Dan Shaw suggested that we do a follow-on grant for a little more to cover the cost/time of promoting the plugins and encouraging more such work after it is done.

**Comment by conor10** [comment]
Ideally, I'd like to see the promotional part a condition of the grant, just so we can be sure it doesn't get forgotten about.

**Comment by Souptacular** [comment]
Voting has completed. This grant is **Approved**.

The following TSC members voted in favor of this grant:

- Hudson Jameson (@Souptacular)
- Anais Ofranc (@Consianimis)
- Conor Svensson (@conor10)
- John Wolpert (@humbitious)
- Stefan Schmidt (@stefschmidt)
- Tomasz Stańczak (@tkstanczak)

**Comment by humbitious** [comment]
How is this work proceeding, @biscuitdey ?
