### ISSUE TITLE
[GR5] Mobile Money B2B Integration with Baseline Protocol - Use Case

### ISSUE THREAD

**Issue by ahmadoutoure** [eea-oasis/baseline-grants#19]
## Grant name
Mobile Money B2B Integration with Baseline Protocol - Use Case

## Applicant background
Ahmadou El Becaye Toure is an experienced IT and cybersecurity professional in the Telecom and Fintech industries, currently based in Senegal. He has significant expertise in IT audit and cybersecurity operations management, having worked in different roles for a number of large international groups for the last 15 years. 
Ahmadou started his career with the main telecom operator in West Africa. This operator is currently the biggest Mobile Mobile Service provider on the continent.
He is currently Group Head of IT Support and Production for an international microfinance institution based in Paris with subsidiaries in Africa (Nigeria, Senegal, Tunisia, Mali, Ivory Coast, Madagascar, DRC, Burkina Faso) and in China (Nanchong, Sichuan). 
As part of his role, Ahmadou actively participates to the digital transformation  and development of the company including:
•	 Channel Network management optimization (quality of agents monitoring system, profitability etc).
•	Setup of a new distribution channel: mini branches.
•	Executive committee orientation 
Ahmadou has been a conference presenter at ISACA for Africa CACS a number of times and has also been appointed in ACL Customer Advisor Board USA.

##  Overview

Digital Financial Services is one of the sectors with the highest growth rate in recent years.  In Africa and Asia, many users are increasingly using digital means of payment, in particular the eWallets of Mobile Money Providers. According to GSMA , the mobile money monthly transaction value in Africa reached ~$45 billions representing a volume of 3.7 billions of transactions.
There are B2B actors operating in the industry to handle activities such as integration between retail merchant systems and mobile money providers so that bulk disbursement, cash-in,cash-out are possible. However pioneer deployments have shed light on a number of challenges and opportunities for improvements.
We propose to evaluate the suitability and feasibility of using the Baseline Protocol to tackle those technology challenges and simplify the integration process between the different stakeholders. 

## Motivation

Currently there are many providers that are proposing solutions and services to integrate Mobile Money Service Providers and merchants.  For almost all of these solutions, providers are integrating first with all the Mobile Money Service Providers or the main ones in order to consolidate all their services and provide a single platform to the merchants.
It is important to notice that every integration is a full lengthy and very costly project.
This why is this project will be interesting, in fact a normalized interconnection solution based on the Baseline Protocol could benefit all stakeholders.  In order to integrate and interconnect a service of Mobile Money Service Provider and a merchant will need just to be “Baseline ready”.
This goal is not to replace providers proposing integration and interconnection services because they are proposing an important feature for merchant: float account unification. The goal is to understand and analyse the business value of having a standard way to integrate so that we can reduce both cost and duration of integration project. The economic benefit for all stakeholders is that the fastest the interconnection is operational, the faster revenue can be generated from it.  
At the moment, Money Service Providers are actively developing merchants payments, so it is timely to investigate a way to facilitate and simplify those initiatives.

## Execution risks

Time allocation for the tasks.

## Downsides

It might take us longer to design the solution than what we originally planned for, we will mitigate that by providing transparency from the start and manage it.

## Tasks and schedule (milestones if applicable)

The project could be planned for 2 months starting ideally mid of May after approval.
1.	Market study                                              10 hours 
2.	'as is’ industry use case documentation     15 hours
3.	Use case solution design that providing an overview of what an end-to-end implementation could be.                                   25hours
4.	Final report                                                    5hours

## Budget and justification

USD $9,130 will be need for this proposal. This corresponding to an hourly rate of $166 what is an acceptable rate for involved resource in this project.

**Comment by GoldenBit0** [comment]
Cancelled
