### ISSUE TITLE
[GR6] Publishing Supply Chain Improvement Proposal - Michael Cairns

### ISSUE THREAD

**Issue by mpcairns** [eea-oasis/baseline-grants#20]
## Grant name
Publishing Supply Chain Improvement Proposal

## Applicant background

Michael Cairns is CEO/founder of Information Media Partners which he established in 2006. His company advises private equity, information and educational publishing companies, and other content-related businesses seeking expertise and improvement in business operations, investment strategy and digital transformation. Clients of Information Media Partners include Book Industry Study Group, Wolters Kluwer, American National Standards Institute and other similar brand-name publishing clients.

As CEO at Ingenta plc, a software and professional services business, Michael successfully reorganized the business, launched several new products (including the company’s first SaaS software service) and led a funding effort which raised $15mm in new investment. Earlier in his career at Reed Elsevier, Michael managed the divestiture of information publisher R.R. Bowker to Proquest and was subsequently named President. At Bowker, he effectively managed a complete digital transformation of the business, entered new markets and completed six acquisitions, thereby creating a growing, profitable business and tripling enterprise value.

Prior to Bowker, Michael was a manager in the Entertainment and Media Practice at Price Waterhouse Coopers where he provided consulting services to media clients including R.R. Bowker, InterPublic Group, Turner Broadcasting and Ogilvy & Mather.

## Overview

The US publishing market is estimated to represent approximately $35 billion in annual revenue and is highly concentrated with the top 100 publishers comprising over 85% of the market. It is estimated that there are more than 100,000 publishers registered in the US. In addition, the retail market and publishing supply chain are also concentrated on a small number of industry players. Despite this concentration, the business of publishing still operates inefficiently compared with other consumer markets. In particular, product data exchange between trading partners is problematic as is the related process of vendor payments, credits and returns.

The management and communication of product information (metadata) required for inventory management, product ordering and catalog management relies on transmitting files between trading partners on a ‘push’ basis. Many companies within the supply chain duplicate the effort of others in the organization, compilation and management of product information. These efforts cause duplicative costs as well as data quality issues and inconsistencies in product information.
The publishing industry has developed a standard approach to managing product metadata and have supported an initiative named ONIX. However, while ONIX is the recognized standard it is mostly used by the top 50-100 publishers. Of these, only a few operate on the current version (3.0) of the format. Staying current to the most recent version requires investment, which is frequently beyond the resources of publishers outside the top 100. As a result, there are three versions of the ONIX format in general use and receivers of ONIX-formatted files must be able to import ONIX files in all three formats. Publishers outside the top 100 submit data to trading partners in a variety of formats but most frequently in Excel.

Publishers also tend to sell through retailers on long terms and offer generous returns policies. (Non-publishing observers have described this as “consignment selling”). The payment and payment reconciliation processes are very cumbersome and complicated by flexible returns policies. The UK publishing industry operates a service which consolidates invoicing and payment information between trading partners. This service allows a bookseller to view outstanding invoices from multiple trading partners, agree which invoices to pay and then transmit one payment transaction via the service. In turn, the service pays the individual invoices on behalf of the retailer. This has benefits for both the retailer and publisher/wholesaler. The retailer can better manage their cash flow and reduce administrative costs by transmitting only one payment per month. The publisher benefits because they get more predictable cash flow, can automatically match payments to invoices (line items) and identify problems/questions with retailers in an easier way. This system does not operate in the US but could be beneficial here if standard processes were in place.

## Motivation

This project proposes to determine, with key industry players, the extent of the inefficiencies in the supply chain with a particular focus on product metadata and payments processing:
• Determine and document the method for managing product metadata and identify other related inefficiencies between trading partners (i.e., invoice and payments processes).
• Determine the roles of relevant parties across the supply chain.
• Estimate the duplication of costs within the industry associated with the management of product information.
• Propose high-level opportunities for improvement and areas for further study and/or action, in collaboration with the
Baseline Protocol team.

Solutions may orient around:
o Cost elimination
o Process improvement
o Opportunity for industry standardization and/or consolidation
o Communication protocols between trading partners

The output (deliverable) from the above will be in the form of a report.

Market and Supply Chain Challenges:

Historically, the publishing industry has underinvested in collaboration and communication especially in the area of supply chain efficiencies and information management. Within the industry there are several companies whose business it is to provide product information to supply chain partners (for a fee) but, in addition to the costs these companies charge for the services, even their own data customers and data suppliers have duplicative costs related directly to the way they manage and distribute product information.

As Amazon.com became a powerhouse in the industry, publishers and others began to recognize the value of better product metadata and more efficient processes to manage this information. However, while data quality has improved over time, the industry still operates inefficiently with respect to the management and distribution of product data. For example, there is no recognized ‘product master’ for title information and any supply chain participant is likely to apply their own set of quality, editorial or other standards. This results in significant variation in data quality across the supply chain. In addition to duplicative costs this also represents potential lost revenues for products which cannot be found (because of sub-standard and/or outdated metadata) by customers.

Efforts to consolidate suppliers of data and other efforts including data synchronization have been explored in the past and may be solutions for our research to explore with interviewees.

As noted above, the UK has an industry-wide initiative (Batch.co.uk) which has consolidated invoicing and invoice payment processes and materially improved efficiencies between trading partners.

## Execution risks

• A better approach to ensure consistency of product metadata between trading partners is a recurring theme in the publishing supply chain. A risk may be related to exhaustion in discussing the subject.
• Incomplete understanding of the full capability of the Baseline Protocol. This can be addressed by engaging with the Baseline TSC and the wider Baseline Community.

## Tasks and schedule (milestones if applicable)

Most of the information will be gathered by interview. We anticipate meeting between 15-20 industry experts. Each interview and follow-up are expected to take between 60-90 minutes. We have excellent contacts in the industry and once this proposal is approved, we would begin scheduling interviews. We would expect to complete the interview phase within eight weeks. Consolidating our findings into a report for submission and discussion with the Baseline Team would then take place over the following 2-4 weeks. (This latter stage also assumes some additional follow-up with interviewees to clarify and confirm their information). In summary, we expect the project to take between 10-12 weeks.

We would expect to meet with some of the following companies operating in the following sectors:

Trade Publishing: Penguin Random House, Hachette and similar
Education Publishing: Cengage, McGraw Hill, Pearson
Retailers: Barnes & Noble, Amazon.com
Wholesalers: Ingram Book Company, Baker & Taylor
Intermediaries: RR Bowker, OCLC
Industry Associations: Book Industry Study Group, American Booksellers Association

We will seek to interview process and subject matter experts from approximately 15-20 companies and organizations (depending on availability).

## Budget and justification

• Preparation: Identifying candidates, creating interview guide and scheduling interviews 5 hours
• Conduct 15-20 Interviews 20 hours
• Prepare analysis and draft report 8 hours
• Present findings and hold discussion with Baseline 2 hours
• Write and submit final report 5 hours
(The above hours are estimates for planning and budgeting purposes)

$10,000.00 for 40 hours work which is consistent with typical US rates.

Payment to be tied to deliverables as follows:

Phase 1: Problem definition, interview guide, target interview lists and interview schedules - $2,500
Phase 2: Conduct interviews and capture findings in summary document. Report to Baseline Team - $5,000
Phase 3: Complete interviews and summaries, complete findings deliverable, complete conclusions and potential next steps - $2,500
Phase 4: Follow-up with Baseline Team on proposed next steps

Proposed Timing:  
Phase 1 - July 1 - August 1: Invoice July 1
Phase 2 - August 1 - September 30: Invoice Aug 1
Phase 3 - October 1 - November 1: Invoice Nov 1 (or end of project)

**Comment by GoldenBit0** [comment]
Phase 1 completed, presented at 11/10/21 General Assembly. 
TSC will vote on release of funds for Phase 1 ($2,500) @ 11/12/21 TSC Session.

**Comment by GoldenBit0** [comment]
[TSC Approval for fund disbursement](https://github.com/eea-oasis/baseline-grants/issues/52) complete.
