### ISSUE TITLE
[GR5 VOTING] Mobile Money B2B Integration with Baseline Protocol

### ISSUE THREAD

**Issue by Souptacular** [eea-oasis/baseline-grants#27]
## Grant name
**[GR5] - Mobile Money B2B Integration with Baseline Protocol - Use Case**

## Applicant
@ahmadoutoure

## Grant Link
[Click Here](https://github.com/ethereum-oasis/baseline-grants/issues/19)

-------------------------------------------------------------------

Committee members: Please vote :thumbsup: if you want to vote to approve this grant or :thumbsdown: if you want to vote to not approve the grant. You vote via the smiley face icon on the top right portion of this text box.

![image](https://user-images.githubusercontent.com/3460120/110418245-cecfbf00-805c-11eb-87ba-5a47b7ecb4eb.png)

**NOTE: Only committee member can vote.**

**Comment by humbitious** [comment]
This has been approved, and @ahmadoutoure has been informed. He will produce an itinerary of deliverables/milestones for TSC to review.

**Comment by GoldenBit0** [comment]
Cancelled
