### ISSUE TITLE
[GR6 VOTING] Publishing Supply Chain Improvement Proposal

### ISSUE THREAD

**Issue by Souptacular** [eea-oasis/baseline-grants#28]
## Grant name
**[GR6] - Publishing Supply Chain Improvement Proposal**

## Applicant
@mpcairns

## Grant Link
[Click Here](https://github.com/ethereum-oasis/baseline-grants/issues/20)

-------------------------------------------------------------------

Committee members: Please vote :thumbsup: if you want to vote to approve this grant or :thumbsdown: if you want to vote to not approve the grant. You vote via the smiley face icon on the top right portion of this text box.

![image](https://user-images.githubusercontent.com/3460120/110418245-cecfbf00-805c-11eb-87ba-5a47b7ecb4eb.png)

**NOTE: Only committee member can vote.**

**Comment by humbitious** [comment]
This grant project has been approved. @mpcairns

**Comment by GoldenBit0** [comment]
Work has been complete, work has been presented at BL show, payment approval complete by TSC, and info shared for fund disbursement.
