### ISSUE TITLE
[Bounty1] Baseline Protocol Grant Proposal RFP for incorporating an Ethereum based DID method into either BRI-1 or BRI-2 or both

### ISSUE THREAD

**Issue by Therecanbeonlyone1969** [eea-oasis/baseline-grants#30]
### Introduction

The Baseline Protocol Standard’s working group has decided to incorporate [W3C Decentralized Identifiers (DIDs](https://www.w3.org/TR/did-core/) and[ W3C Verifiable Credentials (VCs)](https://www.w3.org/TR/vc-data-model/) as key components for identifier, identity, and credential management into the Baseline Protocol Standard. This was done in anticipation of much broader adoption of the Baseline Protocol into supply chains and financial networks often spanning tens of thousands of entities with often limited established business, and thus, trust relationships which in turn requires robust, standardized methods to establish and manage these trust relationships without centralized trust authorities and centralized infrastructure, and without having to operate a heavy technology infrastructure to manage millions or more identifiers and identities in realtime at each entity. This necessitates a decentralized/federated infrastructure with the ability to operate at scale in real-time while also ensuring the highest level of security and data integrity required by enterprises.

There is currently only one protocol standard able to meet these requirements: [The DID Sidetree Protocol developed at the Decentralized Identity Foundation. ](https://identity.foundation/sidetree/spec/)

### RFP Goal

In order to facilitate easier adoption of DIDs in the Baseline Protocol, the Baseline Protocol Technical Steering Committee (TSC) would like to see an integration of an Ethereum based Sidetree DID method in either one of the existing Ethereum based reference implementations -- [BRI-1](https://github.com/ethereum-oasis/baseline/tree/master/examples/bri-1) or [BRI-2](https://github.com/ethereum-oasis/baseline/tree/master/examples/bri-2). 

### RFP Description

There are two separate tasks that should be addressed by RFP submissions:

- The update of the current Ethereum based reference implementation of the Sidetree protocol called Element, which can be found [here](https://github.com/transmute-industries/sidetree.js), to the V1.0 of the Sidetree protocol referenced above. The required upgrade work can be found [here](https://github.com/transmute-industries/sidetree.js/issues/194).
  * Done Criteria:
        1. Test Report showing all required tests of the Sidetree protocol V1.0 passing.
        2. Merged PR of the upgrade in the [Transmute Github Repo](https://github.com/transmute-industries/sidetree.js).

- The integration of the Element DID method into either BRI-1 or BRI-2 or both with a functioning “Hello World” application that demonstrably utilizes the Element DID method between counterparties involved in the “Hello World” application.
  * Done Criteria:
    1. Demo Video of the “Hello World” application showing the usage of the Element DID method.
    2. Merged PR with test fixtures accepted into either of the Baseline Reference Implementation Repos -- BRI-1 or BRI-2. 

An RFP may be submitted for one of the two tasks or both [here](https://github.com/ethereum-oasis/baseline-grants).

Each task comes with a **$20,000** grant from the Baseline Protocol Grant Program.

The Deadline for Submissions is: TBD

The winning submissions will be announced on: TBD

cc @humbitious @kthomas @tasdienes @Souptacular

**Comment by humbitious** [comment]
Grant Proposals based on this bounty please add a new issue and reference this issue.
