### ISSUE TITLE
[GR11] Security Improvements for Excel Addin

### ISSUE THREAD

**Issue by biscuitdey** [eea-oasis/baseline-grants#33]
## Grant name
Security Improvements for Excel Addin

## Applicant background

Biswashree Dey. I am currently working on the development of the Excel Addin.

## Motivation and overview
The Microsoft Office library being used for development has multiple security issues which makes the Addin unfit for production. The library was selected as it is the official library for creating Addins and provides on-going support.
Known Issues:
1. The Addin stores the user credentials within the Excel document causing these to be passed along whenever the user shares their Excel document with a counterparty. Currently, the Addin does not permit data to be stored on the local file system (needs to be developed).
2. Addin allows anyone with access to the communication channels to tamper with the data.

## Execution risks
1. To mitigate the security risks, additional development might need to be done besides the Addin.

## Downsides
1. Development might require longer than expected due to unforeseen additional development.

## Tasks and schedule (milestones if applicable)

|           TASK TYPE                      |                             DETAIL                                                             |                    TIME                  |
|-------------------------------|------------------------------------------------------------|----------------------------|
| Security Analysis                      | Reviewing the Microsoft Office.js library for security vulnerabilities |      3 weeks                |
| Development                             |Secure local storage for Addin                                                   |                  1.5 weeks             |                                                                                                                                                
| Testing                                      |                            Storage functionality                                       |                  3 days                   |
| Development                            | Secure communication for inbound messages                        |              2 weeks                    |                                 
| Testing                                      |                             Communication functionality                        |                  4 days                   |            
| Development   & Testing         |  Additional development as per security analysis                    |              2 weeks                    |   

## Budget and justification
Budget : $7500

Justification : I will be dedicating all my time working on this project. The project will require development of modules to support the security functionality of the Excel Addin.

**Comment by GoldenBit0** [comment]
@biscuitdey Hi, all grant money must be distributed by the Dec 31, 2021. 

Since ~2 weeks for the process of having TSC review work, creating publications on work, TSC vote, and working with the payment team to release funds. Please anticipate having work done by mid December.

Please use this comments section to provide updates on your work each week. Thanks!

**Comment by biscuitdey** [comment]
~14th Nov 2021
Created secure local storage for the Addin using the File System Access API. The user information (user name and token) will be stored locally on a file. Besides this, this information will also be saved in a session and the user information will be deleted every time the user logs out of the session.

**Comment by biscuitdey** [comment]
### List of security measures
1. Email validation
2. Password validation
3. Form input validation
4. Secure storage → local file system
5. HTML encoding
6. JSON encoding
7. JSON validation (Sanitization)
8. IndexedDB secure

**Comment by biscuitdey** [comment]
8. Secure IndexedDB - 50%
      
Implemented encryption to be used with IndexedDB using Web Cryptography API

**Comment by biscuitdey** [comment]
4. Secure storage - 100%
        Storing and retrieving encrypted user information in IndexedDB
8. Secure IndexedDB - 100%
        Implemented encryption and encoding to be used with IndexedDB using Web Cryptography API.

**Comment by biscuitdey** [comment]
1. Form input validation - 100%
    Regex match for valid inputs
2. HTML encoding - 100%
     HTML encoding for input received from client (excel sheet) and server that will be displayed using .innerHTML() to prevent XSS attacks 
3. JSON encoding - This was ultimately not required.
4. JSON validation (Sanitization) - 100%
     Error catching and validation for JSON.parse()
