### ISSUE TITLE
[GR11 VOTING] Security Improvements

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-grants#36]
Please vote on Grant Proposal #33 

Total for this project: $7500

Vote yes with thumbs up icon. Vote no with thumbs down. Abstain with eyes icon.

**Comment by GoldenBit0** [comment]
Voting complete, majority vote under https://github.com/eea-oasis/baseline-grants/issues/33

**Comment by GoldenBit0** [comment]
Voting complete here- https://github.com/eea-oasis/baseline-grants/issues/33
