### ISSUE TITLE
[GR1] - Baseline Plugins (Excel & Oracle)

### ISSUE THREAD

**Issue by biscuitdey** [eea-oasis/baseline-grants#4]
## Grant name

Baseline Plugins (Excel & Oracle)

Create baseline plugins for Excel and Oracle

## Applicant background

Biswashree Dey

## Motivation and overview

I run a startup that requires the Excel and Oracle Flexcube plugins for baselining the trade finance transaction process of the banks. Banks use Excel and Oracle Flexcube for reconciliation and settlements of transactions.

## Execution risks

1. Inability to complete the task on time
2. Miscalculating the scope of work
3. Miscalculating the utilization of TypeORM

## Downsides

1. I will be working alone
2. Time required to understand the overall Baseline architecture

## Tasks and schedule (milestones if applicable)

Total time : 6.5 weeks

|           TASK TYPE                      |                             DETAIL                                                             |                    TIME                  |
|-------------------------------|------------------------------------------------------------|----------------------------|
| Knowledge gathering               | Overall understanding of Baseline + Analysis of TypeORM    |                  2 weeks                |
| Development                             | 1. CRUD on Excel  2.Alert, subscribe, unsubscribe and query on Excel | 1.5 weeks             |                                                                                                                                                
| Testing                                      |                                Excel                                                              |                  3 days                   |
| Development                             | 1. CRUD on Oracle (using TypeORM)  2.Alert, subscribe, unsubscribe and query on Oracle|              2 weeks                    |                                 
| Testing                                      |                                Oracle                                                            |                  4 days                   |            

## Budget and justification

Budget : $2500

Justification : I will be dedicating all my time working on this project.

**Comment by humbitious** [comment]
This was approved in #12 .

**Comment by GoldenBit0** [comment]
Unanimous vote for funds disbursement complete at 10/29/2021 TSC meeting.
