### ISSUE TITLE
[GR] Baseline Protocol - Project Documentation - Improvement

### ISSUE THREAD

**Issue by anaisofranc** [eea-oasis/baseline-grants#42]
TSC Members: Please vote yes with thumbs up icon. Vote no with thumbs down. Abstain with eyes icon.

## Grant name
Baseline Protocol - Project Documentation - Improvement

## Applicant background
Consianimis is a consulting practice with significant experience in programme and project management. Our work focuses on advising and delivering on complex digital transformation initiatives. Our founder, Anais Ofranc is a member of the TSC and therefore will abstain from voting on this proposal.

## Overview
We are proposing to review and improve the Baseline Protocol project documentation.

Deliverable 1: Content for https://docs.baseline-protocol.org (30%)
Improvement will be based on the gaps/issues that we have identified and on some of the recommendations proposed by Tom Lyons (see #11 ). We will prioritize items such as the creation and addition of an onboarding section (paths for Devs and non Devs), creation and addition of a comprehensive FAQ, and update of least up-to-date sections.

Deliverable 2:  V.1 Roadmap Development kick-start (70%)
This will be based on workshops with Core Devs as well as gaps/issues that we have identified. Activities will also include review, cleanup and update of Baseline Protocol repos (‘baseline’, ‘roadmap’, ‘outreach’ and ‘standard’).

## Motivation
Consianimis believes in the potential of the Baseline Protocol. We have been contributing to the initiative for a year. We have the required level of visibility and understanding needed to deliver this project.
In addition, the TSC stated many times that this work needed to be done and as far as we are aware, nobody else has volunteered or proposed to undertake it.

## Execution risks
This proposal assumes that there are currently no volunteer contributors undertaking this piece of work. If members of the community start actively contributing during the execution of the project, we will coordinate with them to avoid duplication of work and doc conflict.
Deliverable 2 is in part dependent on stakeholders' availability. We will aim to capture and articulate as many requirements as possible within the allocated time frame.

## Downsides
There are no downsides to the improvement of the Baseline Protocol documentation.

## Tasks and schedule (milestones if applicable)
The two deliverables will be worked on in parallel and will be fully delivered 1 calendar month after approval of the proposal. 
We propose to set a checkpoint mid-project (i.e 2 weeks after the start of the project) to provide updates and get feedback from the TSC.

## Budget and justification
USD 6,000 for 40 hours of work.

**Comment by anaisofranc** [comment]
@humbitious - New grant proposal submitted.

**Comment by Consianimis** [comment]
Update: List of tasks and progress for this grant can be viewed here :  https://github.com/eea-oasis/baseline/issues/382
