### ISSUE TITLE
Grant Project Progress Reporting: Sidetree update to Spec v1.0

### ISSUE THREAD

**Issue by Therecanbeonlyone1969** [eea-oasis/baseline-grants#45]
Starting with a September progress report during the 1st week of October, Transmute is to provide a monthly progress update no later than the 1st Friday of the month by leaving report comments with relevant documents on this issue.

The progress report must answer the following questions:

1. What was achieved during the previous month by achieved deliverable
2. What is intended to be achieved during the upcoming month
3. Are there any blockers / issues that would impact the delivery timeline of 12/31/2021, and if yes, what are they, and what are the mitigation measures taken to mitigate the risk.

cc @or13

**Comment by OR13** [comment]
### Last Month

Generated and confirmed test vector interop with ION

https://github.com/transmute-industries/sidetree.js/pull/247

### Next Month

We're hoping to clean up the project, recover some helpful tests, especially related to interfaces for storage and ledger.

We're hoping to submit M1 deliverables.

We're also hoping to start on explorer ui and dockerization 

### Blockers

Some fear over the "value locking" mechanics related to ION that happen to be embedded in sidetree core..

They are not 100% appropriate for systems like ethereum.

We believe this can be mitigated by excluding that functionality, as we have done so to date.

**Comment by OR13** [comment]
### Last Month
- Update commitlint: https://github.com/transmute-industries/sidetree.js/pull/257
- Fix circular dependencies in core: https://github.com/transmute-industries/sidetree.js/pull/268
- Begin dashboard application: https://github.com/transmute-industries/sidetree.js/pull/260
- Remove download hack: https://github.com/transmute-industries/sidetree.js/pull/269
- Fix CAS unit tests: 
- https://github.com/transmute-industries/sidetree.js/pull/259
- https://github.com/transmute-industries/sidetree.js/pull/262
- https://github.com/transmute-industries/sidetree.js/pull/264
- Create ledger tests with Element: https://github.com/transmute-industries/sidetree.js/pull/265
- Fix mock CAS Unix FS: https://github.com/transmute-industries/sidetree.js/pull/267
- Clean package dependencies: https://github.com/transmute-industries/sidetree.js/pull/270
- Remove core duplication from common interfaces: https://github.com/transmute-industries/sidetree.js/pull/271

### Next Month 

- Release docker configuration for running Element
- Release node operators documentation for Element
- Implement Sidetree node rest API
- Create UI or CLI for exposing Sidetree node rest API

### Blockers

There are no blockers or issues that would impact the delivery of the timeline of 12/31/2021.

**Comment by OR13** [comment]
### Last Month

Complete:

- Contains a ledger agnostic interface for Sidetree and a test suite that a Sidetree ledger implementation must pass [(link)](https://github.com/transmute-industries/sidetree.js/tree/main/packages/ledger)
- Capture test vectors for v1 from ION [(link 1](https://github.com/transmute-industries/sidetree.js/blob/main/packages/test-vectors/src/wallet/v1-secp256k1-operations.json) & [link 2](https://github.com/transmute-industries/sidetree.js/blob/main/packages/wallet/src/__test__/generate-operation-fixture.test.ts))
- Develop TDD tests for ensuring v1 conformance (link)
- Run depcheck and remove unused deps [(link)](https://www.npmjs.com/package/depcheck)
- Trace through a Write operation to be able to create new did:ion:test [#286](https://github.com/transmute-industries/sidetree.js/pull/286/files)
- Wire dashboard transactions API and UI [#283](https://github.com/transmute-industries/sidetree.js/pull/283)
- Dashboard API [#278](https://github.com/transmute-industries/sidetree.js/pull/278)
- Chore(element): dashboard element ganache testing resolve [#282](https://github.com/transmute-industries/sidetree.js/pull/282)
- Create operation explorer UI [(link)](https://github.com/transmute-industries/sidetree.js/tree/main/packages/dashboard/pages/operations)
- Create resolver interface[ (link)](https://github.com/transmute-industries/sidetree.js/tree/main/packages/dashboard/pages/%5Bdid%5D)
- Create wallet UI [(link)](https://github.com/transmute-industries/sidetree.js/tree/main/packages/dashboard/pages/wallet)

Complete; continuing to refine:
- CI/CD for sidetree.js is turned on and passing 
- Setup Raspberry PI Element Image 
- Tag as pre-release major version 
- Release docker configuration for running element 
- Release node operators documentation for element 
- Deploy v1 workbench container to GCP for element 
- Fix sidetree.js theme config/light and dark mode 
- V1 Element testnet docker image has been published 
 
### Project Completion
Transmute has completed both milestones within the Baseline grant to update Element to v1.0 of the Sidetree Protocol. All updates made can be found in the Sidetree.js repository. 

Transmute presented at the General Assembly forum on December 8th to share to the community the work that was completed and how Transmute continues to lead in open-source standards. 

We thank Baseline for the opportunity!

Obviously open source work never finishes, we welcome new contributors issues, pull requests and critical feedback.
