### ISSUE TITLE
[GR15] Battleship Hello World for Developers

### ISSUE THREAD

**Issue by jackproudfoot** [eea-oasis/baseline-grants#51]
## Grant name
Battleship Hello World for Developers

## Applicant background

| Name | Technical Expertise |
| ---- | ------------------  |
| Manik Jain  | 8 years as full stack BlockChain developer and researcher. Won 2 Cardano Catalyst Fund proposals, and working on to solve the BlockChain metadata problem.   |
| Jack Proudfoot  | 3 years as full stack developer.   |
| Stefan Kostic | 6 years as full stack web and BlockChain developer. Working as Baseledeger Lakewood developer. |
| Ryan Fisch | VP of Engineering at Consensys Mesh, with previous experience as a Solution Architect at Consensys and specifically as part of the Baseline Protocol Oasis Open Project.  |
| Daven Jones | Product Owner at Provide Technologies. Has led Product teams in the enterprise blockchain space since 2017. |

## Motivation and overview

The goal is to create a project designed to onboard developers to Baseline. The project should be lightweight and easy to run. 

The idea is to create a simplified version of the classic game Battleship. At the start of the game players place a single ship on their hidden grid. Then the players take turns making guesses on the location of their opponents ship. In this example the players would represent an organization and the outcome of a guess (hit/miss) will be verified using zero knowledge proofs.

Please check this BLIP for more details: https://github.com/eea-oasis/baseline-blips/issues/7

## Execution risks

- Existing examples use circom/snarkjs. Need to explore use of Gnark instead.

## Downsides

None (?)

## Tasks and schedule (milestones if applicable)

Initial version ready by 12/8/21 

Steps
1. Explore existing zk battleship examples
2. Write circuit for simplified version of battleship game
3. Build frontend that implements/interacts with Baseline stack
4. Write developer-friendly explanation on frontend explaining how baseline concepts relate to the battleship example

## Budget and justification
USD $10,000 for the work requiring research, front end development, circuit development, circuit integration.

**Comment by GoldenBit0** [comment]
TSC will review grant proposal & 'thumb's up' to upvote.

**Comment by skarred14** [comment]
Will this be considered as a different form of BRI? Or is this more of a refinement of the baseline stack in lieu of this use case?

It would be helpful to elaborate a little on the implications of this use case.

@jackproudfoot @humbitious @GoldenBit0
