### ISSUE TITLE
[GR-38 APPROVE RELEASE OF FUNDS ] Baseline Protocol - DIDS Sidetree for Ethereum Update by Spruce - Grant 38 

### ISSUE THREAD

**Issue by GoldenBit0** [eea-oasis/baseline-grants#56]
Grant Proposal: #38
Grant Work: Updates from team can be found here (please read most recent update), #46 
Presentation of findings: Team presented at Baseline December General Assembly

Fund Release: $20,000 to Spruce 

TSC Members vote with thumbs up icon or thumbs down icon on approving release of funds for completed Grant 38 work by Transmute.

**Comment by kthomas** [comment]
This was such an amazing project and experience working with Spruce...

Thanks to everyone who made it happen!
