### ISSUE TITLE
Baseline Protocol - Complete Website Overhaul and Future Maintenance

### ISSUE THREAD

**Issue by boye** [eea-oasis/baseline-grants#62]
## Grant Title
Complete Website Overhaul and Future Maintenance

## Details on Grant Work
The work for this grant entails the complete overhaul of the official Baseline Protocol website (i.e. baseline-protocol.org) and all necessary changes, updates, patches et cetera in the near future. Also, some of the grant will be reserved for the support during the possible migration to Wordpress (or perhaps the integration of a headless CMS?).

## Motivation and Overview
The content presented on the previous website was rather limited and its UI (User Interface) somewhat outdated. Under the hood (i.e. the client-side code) there was also room for improvements.

## Value to the Baseline Protocol
A modern looking, good performing and user friendly website is IMHO essential to get the right message across. Also, if the website is being built properly (i.e. with optimal performance and SEO) it will get a higher page rank in search engines and therefore will result in more eyes on the Baseline Protocol.

## Downsides / Execution Risks / Limitations
Being the only dev doing future work (although I think this will be not a risk anymore very soon according to Sonal).

## Deliverables / Schedule / Milestones
TASK TYPE | DETAIL | TIME
-- | -- | --
Research | Some high-level research into Hugo (the SSG used by the previous site) | 4 hours
Front-end Development | The complete overhaul of the website | 4 weeks
Maintenance | Future updates (both content as well as code) | 4 hours per week (one year long)
Future Development | Support during the possible migration to Wordpress or the integration of a headless CMS | ?

## Budget and Justification
USD $10,000 in total for the work requiring research into Hugo, the actual overhaul (i.e. front end development), future updates (both content as well code) and the support during a migration to Wordpress or integration of a headless CMS.

Phase 1: USD $5,000 (the initial overhaul, already being done)
Phase 2: USD $5,000 (all future developments)

Note: to implement future updates I (Boye) will reserve **four** hours per week for the whole year (2022).

## Applicant Background
[Boye Oomens](https://www.linkedin.com/in/boyeoomens/)
Seasoned front-end developer with over fifteen years of in-depth web development experience and passionate about web standards. Graduated in 2008 from the Rotterdam University (Media Technology, BICT). Always aiming for semantic, cross-browser & cross-platform consistent and maintainable code.

### Community Grant Agreement 
I understand and agree to the ['Process for Approved Grants' outlined here](https://github.com/eea-oasis/baseline-grants/blob/main/README.md)
- [x] I agree 
- [ ] I do not agree

**Comment by humbitious** [comment]
Should have regular milestone reporting.

**Comment by GoldenBit0** [comment]
Please review grant application & vote (thumbs up for approval, thumbs down for disapproval).
@samratkishor @Therecanbeonlyone1969 @skarred14 @kthomas @caleteeter @mehranshakeri @fosgate29

**Comment by samratkishor** [comment]
+1 for milestones / periodic review e.g. quarterly performance metrics discussion and identification of improvement opportunities.

**Comment by fosgate29** [comment]
+1 for milestones

**Comment by boye** [comment]
Just to chime in quickly. I have set up a [GTMetrix](https://gtmetrix.com/) account just for baseline-protocol.org and it will provide weekly reports concerning the performance. Also, if the performance takes a hit (for whatever reason) it will set off an alarm.

Today I will sync with @claurau to implement Google Analytics so we can monitor even more metrics.

**Comment by GoldenBit0** [comment]
**Grant Issue Tracker as Outreach Work Item -** https://github.com/eea-oasis/baseline-outreach/issues/19

**Comment by boye** [comment]
After consulting with @GoldenBit0 we agreed to bring the grant allocation for phase 2 down to $2,500. This is mainly because of the limited maintenance and not moving forward with the migration to Wordpress.

**Comment by boye** [comment]
Reopened the issue (after I accidentally closed it)
