### ISSUE TITLE
Grant Payment Request - Baseline Protocol Website Overhaul Phase 1

### ISSUE THREAD

**Issue by boye** [eea-oasis/baseline-grants#65]
# Grant Payment Request
Grant payment request is submitted once the grant project has been completed as specifed in the grant application (or as agreed upon by grant recipient and TSC if there was a scope change). 

The payment has been approved if a majority (6 or more) of the Technical Steering Committee members upvote this request(thumbs up).

## Grant Title
Baseline Protocol Complete Website Overhaul Phase 1

### Grant Application
Issue #62 

### Grant Work Tracker
N/A

### Links to Final Deliverables
https://baseline-protocol.org

### Grant Amount
USD $5,000 

### Notes
N/A

### Payment Request Status
Payment request is approved if 6 or more TSC members have upvoted (thumbs up) this issue.

**Comment by GoldenBit0** [comment]
Work, approval & payment complete.
