### ISSUE TITLE
[GR2] No-Code Hello World Application 

### ISSUE THREAD

**Issue by tuvalusoftware** [eea-oasis/baseline-grants#7]
## Grant name
No-Code Hello World Application 

## Applicant background
QModeler - is a team of 12 blockchain developers working accross the world. We have been working on blockchain projects for 4 years and have built the leading blockchain No-Code development platform QModeler.
 

## Motivation and overview
Adapting our product to the Baseline Protocol will provide our customers with added comfort and reassurance as well as various other benefits, such as the potential of future integratons,that are accrued by adhering to a standard.  For more about the many benefits our customers find in using our market leading product please view our explainer video at the link below.The baseline protocol would benefit by a potentially wider adoption as a consequence of being available to a non-technical audiance. 
Our proposal is to build a Hello World application in our No-Code Platform that deploys to the Ethereum mainnet. This would entail adding new components to our pallet of components and some backend changes that would modify our own architecture that uses a different approach to synching merkle trees. Once built technically nieve users would be able to build sophisticated applications using a drag and drop interface. 

https://www.youtube.com/watch?v=njce9Q9hhMc

## Execution risks
- integration with our proprietary formal verification could involve modification of contracts. 
- documentation of the code is scarce but we can learn the code. 

## Tasks and schedule (milestones if applicable)

Milestone  1 -  Modification of QModler Runtime to include  messaging JSON-RPC.
Milestone  2 -   Modification of QModeler Runtime to include persistance libraries
Milestoone 3 - Integration of QModeler Smart Contracts and Baseline Smart contracts. 

## Budget and justification
10,000 USD 
We anticipate the work would take 4 backend developers 2 blockchain developers and 4 UI developers working in parallel for 5 weeks. 
Our cost is estimated to be  50K

**Comment by Souptacular** [comment]
Under the `Budget and justification` section you list 10,000 USD, but then say your cost is estimated to be 50k. Are you asking for 10k or 50k from the grant? Thank you.

**Comment by tuvalusoftware** [comment]
I am asking 10,000 USD to defray costs and my company will absorb the remainder of the costs.  One note though, Some features of our product QModeler which are unrelated to the baseline protocol will not be available open source.

**Comment by humbitious** [comment]
Tim, you should join us on the Steering Committee meeting or soon to discuss and defend the proposal, so that the TSC can vote on it.  Tomorrow is the next meeting (Monday, April 12). Reach out to me on Slack to get an invite, if you don't already have one.  Meeting is at 11am US-Eastern on Zoom.

**Comment by humbitious** [comment]
Is this still live or should we close the issue?
