### ISSUE TITLE
Attend - Lendit Fintech - The USA’s Leading Event for Innovation in Financial Services. May 25-26

### ISSUE THREAD

**Issue by BresGit** [eea-oasis/baseline-grants#71]
## Grant Title
Attend - Lendit Fintech - The USA’s Leading Event for Innovation in Financial Services. May 25-16
https://www.lendit.com/usa/2022/

## Details on Grant Work
Attend Keynotes (bellow is what I selected, but I could attend others as recommended by the team)
Summarize key notes
Present summary information at The Baseline Show
Approach presenters/attendees to inform and discuss potential Baseline participation/engagements
Share all contact information with the Baseline Team
Join Baseline Show from the conference on May 25. 

LenditFintech is considered the biggest fintech of the year, expected 350 speakers.
Attend  Keynote Speakers
Chime
Chris Britt
Co-founder & CEO @ Chime
We’re changing the way people think about banking
Chime is a financial technology company founded on the premise that basic banking services should be helpful, easy and free. We want to profit with our members, not from them. That’s why our model doesn’t rely on overdraft fees, monthly service fees, service fees, minimum balance requirements, and more.
We partner with regional banks to design member first financial products. This creates a more competitive market with better, lower-cost options for everyday Americans who aren’t being served well by traditional banks. We help drive innovation, inclusion, and access across the industry.
 
Figure
Mike Cagney
Co-Founder & CEO
Transforming financial services through blockchain technology
Figure is transforming the trillion–dollar financial services industry using blockchain technology. In three short years, Figure has unveiled a series of fintech firsts using the Provenance Blockchain for loan origination, equity management, private fund services, banking and payments.

Mastercard
Sarah Clark
SVP Digital Identity
Its very exciting that conferences are back, I am looking forward to speaking as one the opening day keynotes at LendIt USA - taking place at the end of May in NYC - in a session called "Can Financial Services Replicate the Amazon Experience?" Digital Identity done right transforms sharing proof of identity as well as other credentials into a "one click" user experience with a higher level of trust for all parties and can also drive increased personalization. I'm looking forward to sharing more on this as well as hopefully seeing many of you in person at the event and perhaps for a glass of wine

Lili
Lilac Bar David
CEO & FounderLili is the all-in-one banking app designed for your business. Voted in the Top 50 World's Most Innovative Companies in 2022 by Fast Company. By combining a checking account with technology to save on taxes and accounting software, Lili is an all-in-one mobile banking app designed to save time and money for anyone who runs a business on their own, freelancers and small businesses alike. *Lili is not a bank. Banking services provided by Choice Financial Group, Member FDIC.

## Motivation and Overview
Introduce & inform potential contributers & users where and how the Baseline Protocol can be used and advantages of Baselining.  Concentrate on attendees that have existing business processes across multiple parties.

## Value to the Baseline Protocol
Bring on board new contributors & users
Recognize new Use Cases
Recognize new Baseline requirement/features to be included

## Downsides / Execution Risks / Limitations
I will not be available to attend as a result of my personal schedule. The conference is canceled.

## Deliverables / Schedule / Milestones
Attend Lendit Fintech May 25-26.
Present summary of the Key Notes and  all relevant gathered information at the Baseline Show on  June 8.

## Budget and Justification
Standard Rate to attend - $2,995 (Expires May 24) 

## Applicant Background

Boris Breslav. Experienced professional (Business Analyst/Project Manager) with over 15 years of  experience in the financial industry. Participating/watching the Baseline  Show for the last two years.  
Completed grant 2021 Proving Request for Quotes (RFQ) of Bonds Under Zero Knowledge

### Community Grant Agreement 
I understand and agree to the ['Process for Approved Grants' outlined here](https://github.com/eea-oasis/baseline-grants/blob/main/README.md)

- [X] I agree 
- [ ] I do not agree

**Comment by Sjaaaakster** [comment]
If approved, 

i hope you will be sure that your personal schedule matches the dates of the summit. And i would add a sort of blogpost style review about your observations which could be published on our socials.

**Comment by GoldenBit0** [comment]
Grant request approved with majority upvote by TSC.

**Comment by Therecanbeonlyone1969** [comment]
@GoldenBit0 ... you need 6 upvotes
