### ISSUE TITLE
[GR] AmsterBased Grant

### ISSUE THREAD

**Issue by samratkishor** [eea-oasis/baseline-grants#73]
# [GR] AmsterBased Event

---

## Details on Grant Work
We conducted our maiden event AmsterBased as part of the Ethereum Foundation's event DevConnect 2022 in Amsterdam in April 2022. We raised funds through sponsorships and conducted a very successful event. The event capacity was 120 and sold-out, with 83 members waitlisted, and also live-streamed across various Baseline channels for virtual attendees (with ~900 views so far).

---

## Motivation and Overview
The grant request is to cover the shortage in the sponsorship money to cover the event's expenses.

---

## Value to the Baseline Protocol
This was our first standalone event and we would like to replicate this success at other places in the world and motivate technology leaders to adopt Baseline.

---

## Downsides / Execution Risks / Limitations
N/A as the event has already been conducted.

---

## Deliverables / Schedule / Milestones
Event has already been conducted on 20th April 2022. Our videos are live and being watched, with ~900 views to date.
---

## Budget and Justification
The total budget of the event was short by 3752 Euros. The money needs to be paid to OASIS and they will pay it to the community members who paid for the service availed in Amsterdam.

## Applicant Background
Samrat Kishor is the TSC Co-Chair and submitting this request on behalf of the event's organizing team.

---

### Community Grant Agreement 
I understand and agree to the ['Process for Approved Grants' outlined here](https://github.com/eea-oasis/baseline-grants/blob/main/README.md)
- [X] I agree 
- [ ] I do not agree

**Comment by GoldenBit0** [comment]
Grant paid.
