### ISSUE TITLE
Payment Request - LendIt FinTech Grant [#71]

### ISSUE THREAD

**Issue by GoldenBit0** [eea-oasis/baseline-grants#78]
---

## The USA’s Leading Event for Innovation in Financial Services. May 25-26.

---

### Grant Application

Issue # https://github.com/eea-oasis/baseline-grants/issues/71

---

### Grant Work Tracker

https://github.com/eea-oasis/baseline-outreach/issues/22
---

### Links to Final Deliverables

- Details can be found at https://github.com/eea-oasis/baseline-outreach/issues/22
- Deep dive at Baseline Show (6/1/22) at https://www.youtube.com/watch?v=HZJj2VJWyMI
- Update at June General Assembly (6/8/22) at https://www.youtube.com/watch?v=wbTKkwVuZas
- Also working with Outreach Team to produce enablement content for contacts met at event to explain baseline and get involvement / sponsorship / interest 

### Grant Amount
Requested amount for work (must match approved application)
$2,995

### Notes
Any questions or comments?

**Comment by BresGit** [comment]
Thank you for the opportunity to attend the Conference.
