### ISSUE TITLE
|GR| Baseline Protocol Research Program

### ISSUE THREAD

**Issue by CryptoHipster** [eea-oasis/baseline-grants#81]
## Grant Application
Grant applications are completed by individuals or teams to propose allocation of Baseline grant funds to a specific project. Please use this application template and submit an issue.

The grant application has been approved if a majority (5 or more) of the [Technical Steering Committee members](https://docs.baseline-protocol.org/governance/technical-steering-committee) upvote this application (thumbs up).

If approved, please add your project to the ['Approved Grants' list here](https://github.com/eea-oasis/baseline-grants/blob/main/Approved-Grants-2022.md).

|GR| Baseline Protocol Research Program

## Details on Grant Work
Every public company, whether in the Fortune 1000 or not, has an inefficient process somewhere within its company. Collectively, these processes may be in the sales departments, the manufacturing assembly line, franchise reporting, middle or back office reporting including settlements and payments, or various accounting, underwriting, or communication processes. Most companies live with these inefficiencies and do not resolve them, rather simply cut headcount and lessen their expenses. These cost cutting measures do not solve the inefficiencies that continue to persist.
If the managers in these companies were made aware of a simple solution to their efficiency problems, such as the Baseline Protocol, many would be interested in adopting this solution, and some may just take it on as one of their technology project initiatives.
In order to get the awareness out there, it requires organic awareness and communication. Not expensive Public Relations campaigns, per se, rather education, information creation and dissemination, and continuous messaging, and materials presented in clear, easy to understand and easy to internalize approach.
The scope of this program should be four-fold:
Creation of research articles and educational materials.

## Motivation and Overview
Enterprise adoption occurs in different ways. With hedge funds and banks, it has been dependent upon reducing investment risks. With payment companies, it has been reliant on addressing regulatory matters. 
But what about enterprise operations? Public company inefficient processes? How can these companies rely upon blockchain technology to create efficient and effective reporting, communications, accounting, auditing, and streamlined operations? F
From my corporate career experience, which included twelve years at AIG related companies, I’ve seen the importance of developing streamlined efficiencies within organizations makes a major impact on the company’s long-term success. In order to get there, education and awareness are necessary first steps in the process. That’s where developing informational and educational content that can be easily published and produced, and then placed in front of company managers, is of paramount importance. 
Public companies have quarterly analyst calls and quarterly 10Q reports, with many not meeting their expectations. Addressing these missed expectations with timely articles of how the Baseline Protocol can help going forward and then getting these articles in front of the company managers, will make a difference. 

## Value to the Baseline Protocol
Having an experienced, trained, educated and dedicated resource responsible for research efforts toward bridging the divide between crypto native companies and traditional businesses who need to leverage technology for its future success is invaluable. In order to speak of ‘enterprise efficiency’, one has to have that experience. The value is immeasurable and priceless to have someone with direct expertise. 
The word gets out, consistently, and we are able to build an organic audience and client base, with many potential enterprise clients.

## Downsides / Execution Risks / Limitations
The downsides and execution risks are time and resources. A  limitation is the time constraint on the articles and the research time required to complete them. I foresee no issues writing about 8 timely research articles during a six-month timeframe. I have a couple press release engine companies that can help if needed that are inexpensive. 

## Deliverables / Schedule / Milestones
Minimum 8 articles demonstrating different use cases of Baseline Protocol and applying Baseline protocol as potential solution to corporate reported issues in their quarterly earnings reports.
The hope is to take these articles and then in 2023 compile them, along with other research and comments from the Baseline protocol community, and craft them into a book

## Budget and Justification
$6.400 total budget for eight research pieces in a six-month timeframe that will help develop the infrastructure further.  $800 after the completion and submission of each.

## Applicant Background
Jamil Hasan is a five-time blockchain book author, with 182 podcasts under his belt at Irish Tech News. He is a former operations, finance and technology manager at American International Group, and led many projects involved in building the investments reporting division and repaying $180 billion in AIG’s bailout from 2008. Jamil holds a masters degree in finance and built data warehouses and data organizations for 20 years.His LinkedIn profile is at 

## Community Grant Agreement
I understand and agree to the ['Process for Approved Grants' outlined here](https://github.com/eea-oasis/baseline-grants/blob/main/README.md)

 X I agree
 I do not agree

**Comment by GoldenBit0** [comment]
Jamil, I added you to the Research Workgroup meetings and drive. It should help with some ideas for the research.

**Comment by samratkishor** [comment]
> Nice idea. Could you please provide more details regarding the format we should expect the outcome? e.g., published articles in journal X who has audience reaching to a network of N companies in industries A,B, etc.

+1

**Comment by fosgate29** [comment]
It would be also good to have listed in advance some subjects that would be researched and worth an article.

**Comment by CryptoHipster** [comment]
Due to personal reasons, I am not going to be able to continue with this request at this time. Thank you for your consideration. Closing request.
