### ISSUE TITLE
[GR] Baseline Protocol Enterprise Education and Awareness Media Program

### ISSUE THREAD

**Issue by CryptoHipster** [eea-oasis/baseline-grants#82]
Grant Application
Grant applications are completed by individuals or teams to propose allocation of Baseline grant funds to a specific project. Please use this application template and submit an issue.

The grant application has been approved if a majority (6 or more) of the [Technical Steering Committee members](https://docs.baseline-protocol.org/governance/technical-steering-committee) upvote this application (thumbs up).

If approved, please add your project to the ['Approved Grants' list here](https://github.com/eea-oasis/baseline-grants/blob/main/Approved-Grants-2022.md).

Grant Title
[GR] Baseline Protocol Enterprise Education and Awareness Media Program

Details on Grant Work
Every public company, whether in the Fortune 1000 or not, has an inefficient process somewhere within its company. Collectively, these processes may be in the sales departments, the manufacturing assembly line, franchise reporting, middle or back office reporting including settlements and payments, or various accounting, underwriting, or communication processes. Most companies live with these inefficiencies and do not resolve them, rather simply cut headcount and lessen their expenses. These cost cutting measures do not solve the inefficiencies that continue to persist.
If the managers in these companies were made aware of a simple solution to their efficiency problems, such as the Baseline Protocol, many would be interested in adopting this solution, and some may just take it on as one of their technology project initiatives.
In order to get the awareness out there, it requires organic awareness and communication. Not expensive Public Relations campaigns, per se, rather education, information creation and dissemination, and continuous messaging, and materials presented in clear, easy to understand and easy to internalize approach.
The scope of this program will be to build the Baseline Protocol to a better known brand through social media distribution.:
Publication and promotion of the Baseline Show.
Publication and promotion of the Baseline Podcast
Publication and promotion of Baseline Podcast (Open Office Hours)
Facilitating monthly General Assembly meetings
Conduct outreach to both get new guests on the show and follow up to build lasting relationships with the guests.

Motivation and Overview
Enterprise adoption occurs in different ways. With hedge funds and banks, it has been dependent upon reducing investment risks. With payment companies, it has been reliant on addressing regulatory matters. 
But what about enterprise operations? Public company inefficient processes? How can these companies rely upon blockchain technology to create efficient and effective reporting, communications, accounting, auditing, and streamlined operations? F
From my corporate career experience, which included twelve years at AIG related companies, I’ve seen the importance of developing streamlined efficiencies within organizations makes a major impact on the company’s long-term success. In order to get there, education and awareness are necessary first steps in the process. That’s where developing informational and educational content that can be easily published and produced, and then placed in front of company managers, is of paramount importance. 
This program first revives a currently successful show, The Baseline Show, and increases its reach, breadth and scope, geographically and across sectors and industries.
Second, to supplement the Baseline Show, my experience as a podcaster will lend its hand in creating the Baseline Podcast, which we can call Open Office Hours. As part of this, I’ll also be looking to host the monthly General Assemblies.

Value to the Baseline Protocol
Having an experienced, trained, educated and dedicated resource responsible for the communication efforts for its success is invaluable. It’s also much more cost efficient than hiring a PR firm for a series of expensive short-term engagements when they lack the proper corporate and enterprise operational efficiency experience to be a credible reference. In order to speak of ‘enterprise efficiency’, one has to have that experience. The value is immeasurable and priceless to have someone with direct expertise. 
The word gets out, consistently, and we are able to build an organic audience and client base, with many potential enterprise clients.
Building relationships with the show guests also is paramount. It not only fosters goodwill, but also attracts future developers and business partners. These business partnerships will be important to growing and developing the community.

Downsides / Execution Risks / Limitations
The downsides and execution risks are time and resources. I’m confident I can deliver a Baseline Show, Open Office Hours, and General Assembly as the host and facilitator. We should be able to get guests as the protocol participants are global. As podcast host at Irish Tech News from March 2021 to May 2022, I was able to interview guests from over forty countries, so geography was no issue. I will also be able to deliver on the Open Office Hours and General Assembly. So, attendance and guests are always a wildcard, but I have never had a real issue there.

Deliverables / Schedule / Milestones
2 monthly episodes of the Baseline Show between July 2022 and end December 2022.
2 monthly Open Office Hours podcasts between July 2022 and end December 2022.
Facilitate monthly general assembly conferences.
Creation of outreach program to invite guests onto the shows, build lasting relationships and grow the community.

Budget and Justification
$3,500  total budget for the scope of this work,including  time to plan, research, publish, maintenance of equipment, etc.
$500 at start. $500 at the end of each month for six months based on meeting agreed upon criteria (2 shows, 2 office hours, 1 general assembly). .

Applicant Background
Jamil Hasan is a five-time blockchain book author, with 182 podcasts under his belt at Irish Tech News. He is a former operations, finance and technology manager at American International Group, and led many projects involved in building the investments reporting division and repaying $180 billion in AIG’s bailout from 2008. Jamil holds a masters degree in finance and built data warehouses and data organizations for 20 years.His LinkedIn profile is at https://www.linkedin.com/in/jamil-hasan-63bb71

Community Grant Agreement
I understand and agree to the ['Process for Approved Grants' outlined here](https://github.com/eea-oasis/baseline-grants/blob/main/README.md)

X  I agree
 I do not agree

**Comment by GoldenBit0** [comment]
Notes from TSC Meeting:
- Add outreach to bring guests on the show
- Include plan for outreach after the show to facilitate a relationship with guests


Notes from Sonal:
- The allocation of show topics might be flexible each month, where if we get 2-3 guests great but if we have to do 1-2 office hours that works too. The priority is usually to bring guests or have themed shows to diversify and amp up the shows.

**Comment by CryptoHipster** [comment]
Due to a variety of personal factors, not going to be able to continue with this request. Closing request. Thank you for your consideration.
