### ISSUE TITLE
[GR] Conduct the Weekly Office Hours : The Baseline Show

### ISSUE THREAD

**Issue by samratkishor** [eea-oasis/baseline-grants#84]
**Conduct the Weekly Office Hours: The Baseline Show**

**Details on Grant Work**

I would like to continue conducting The Baseline Show and merge India and international shows. I have been hosting the India shows and introduced a format of the show which was appreciated by the great John Wolpert :). I would like to introduce more elements to the show like specific sections and use it as a platform to grow awareness about the Baseline Protocol and provide a safe space for community members to roost, exchange ideas, provide feedback and just talk about everything Baseline!

Here is a mind map that I have created for driving The Baseline Show: https://miro.com/app/board/uXjVOisPrG4=/?share_link_id=2488165318

**Motivation and Overview**

I firmly believe that the Baseline Shows have been a common place for all baseliners to come together and discuss ideas, applaud contributors and discuss the next steps. I have been conducting the Baseline Shows - India for the past 1 year from July 2021 to July 2022 and have seen how it made a profound impact on the understanding and awareness of Baseline Protocol. The format of the show included inviting guests from various walks of life and talking to them about opportunities to use Baseline Protocol in various industries. I would now like to step up and take on the hosting of the Baseline Shows which are conducted at noon EST every Wednesday. The proposal for merging India and international shows has been in motion for a while and I believe this will be a good step to upgrade the audience and prepare well for announcements.

 
**Value to the Baseline Protocol**

The Baseline Shows have been bringing immense value to the Protocol and community members in general. I see the following as the prime value drivers:

1. Community connect
2. Make announcements
3. Promote events and programs like AmsterBased, BLIPs, and Grants
4. Invite high-profile guests and make them aware of the proceedings and hence gain their trust and evangelism.
5. Applaud the great work community members have been doing e.g. core devs, outreach etc.
6. Welcome sponsors and new community members.

**What are the downsides, execution risks, and/or limitations of this work?**

Execution risks include my personal non-availability due to health, travel, or scheduling issues and I plan to mitigate that by having a prior list of speakers at least 2-3 weeks in advance and also being open to pre-recorded discussions which can then be released at the time of the show in the YouTube live.

**Deliverables**

1. 1 Baseline Show per week (including 1 monthly General Assembly) in YouTube live format using simulcasting on LinkedIn, Twitter, and other popular platforms from Baseline Official handles.
2. Simulcasting and posting through my personal social media handles.
3. LinkedIn and Twitter posts pre and post the show.
4. Email communication with guests inviting them to join the community, commit resources, contribute to the grants pool, and potentially become sponsors.
5. I will bear the cost of the podcasting equipment, creatives, subscription of the simulcasting software, and zoom which is used for meetings.

**Budget and Justification**

$1000 per month for the period August 2022 to Dec 2022. (Update: $500 for August)

**Applicant Background**

Samrat Kishor

**Community Grant Agreement**

I understand and agree to the ['Process for Approved Grants' outlined here](https://github.com/eea-oasis/baseline-grants/blob/main/README.md)

   [X] I agree
    I do not agree

**Comment by GoldenBit0** [comment]
@samratkishor can we update the scope for $500 for August given we are halfway through the month?

**Comment by samratkishor** [comment]
@GoldenBit0 absolutely!

**Comment by GoldenBit0** [comment]
Grant approved per majority vote of TSC members

**Comment by GoldenBit0** [comment]
> @GoldenBit0 absolutely!
@samratkishor 
great thanks! please update the values based on what date you'd like to start.

I will be in touch to formalize the process for the stream set up.

**Comment by GoldenBit0** [comment]
Aug - 500
Sept - 1000
Oct - 1000
Nov - 1000
Dec - 1000

Total = 4500
