### ISSUE TITLE
[Clean] BL Grant Proposal RFP #1 - Incorporating DIDs and VCs into Open-Source Digital Asset Wallets

### ISSUE THREAD

**Issue by wsdOgawa** [eea-oasis/baseline-grants#86]
## Details on Grant Work

This was a design that I derived from asking questions on this issue: https://github.com/eea-oasis/baseline-grants/issues/76.
The goal was to try to get an apples-to-apples design of the work being requested in RFP #1. 

## Motivation and Overview

The motivation here was to see if I could create a design that was close to what was being requested.
Working on implementing this would be too much of a detour for how much time I have to work on open source. 

## Value to the Baseline Protocol

Contributing something that takes the text requirements in the RFP and converts it into more clearly defined requirements. (Maybe?)

## Downsides / Execution Risks / Limitations

Limitation: It's just a picture.

## Deliverables / Schedule / Milestones

Milestones:
- [x] Create Issue

## Budget and Justification

Budget: $0
Justification: Posting wireframe design

## Applicant Background
Kousei Ogawa (self) has thirty years of working in the IT industry in Japan working for a large corporation before creating his own company. He has extensive knowledge with working with CentOS and open source technologies. And has been managing the server-side Javascript Application server [Jaxer](https://github.com/WebServiceDevelopment/Jaxer) for business use in Japan under the GPL license.

### Community Grant Agreement 
I understand and agree to the ['Process for Approved Grants' outlined here](https://github.com/eea-oasis/baseline-grants/blob/main/README.md)
- [x] I agree

---

### Network Overview

Below is an image of what I think the network will look like. At the center is the wallet module which would take a mnemonic, hdpath, along with other arguments depending on the function being called. In front of the module would be an Express or other http server that would take the post body from the client, pass them directly into the module and return the response.

There would be two paths served by the http server. One would be the wallet visualization which would combine with data stored locally on the client to provide functionality on the client. And the other path would provide the Swagger/OpenAPI documentation.  

The wallet module itself would require network access to Ethereum, Polygon, Element, Baselin, and IPFS. Either as a service running on localhost, testnet, or production node. 

![BaselineWallet - Network Graph(1)](https://user-images.githubusercontent.com/5275924/187058634-7cb87853-1242-410a-843d-a8d40c821274.jpg)

### Mnemonic

This would be the splash page for the application. That would describe what the wallet is, and define a mnemonic that would be auto-filled for each page as a parameter. There might be a better design on this that allows for multiple mnemonics. My goal here was to try and keep it simple.

![BaselineWallet - Frame 1](https://user-images.githubusercontent.com/5275924/187058819-76a8f083-4478-4659-afe8-cbb6f085a1a7.jpg)

![BaselineWallet - Frame 2](https://user-images.githubusercontent.com/5275924/187058822-0ba51355-e5d3-4c6e-88ad-f55e4118ec2c.jpg)

![BaselineWallet - Frame 3](https://user-images.githubusercontent.com/5275924/187058825-1eb67013-2e85-44e7-8335-dd0107d3de41.jpg)

### did:key

This is not a requirement in RFP #1. `did:key` is useful for debugging, so I included a page for it. 

![BaselineWallet - Frame 4](https://user-images.githubusercontent.com/5275924/187058869-855c2e87-a954-48fb-8bf4-0ee1f674f3c2.jpg)

![BaselineWallet - Frame 5](https://user-images.githubusercontent.com/5275924/187058872-393bd69e-5cb7-4874-9b42-e867b16a8619.jpg)

![BaselineWallet - Frame 7](https://user-images.githubusercontent.com/5275924/187058877-f15d99a2-a6f0-42a5-bab2-978464f7ccd4.jpg)

### Passed and documented tests for DID creation and management for DID Element

In this page I copied what was done in `did:key`. The create part is pretty straightforward, but I'm not sure what requirements would need to be defined for "management". Right now I have create, and deactivate. Not sure how much control over the did is implied, and what design is needed to effectively take advantage of the functionality.

![BaselineWallet - Frame 6](https://user-images.githubusercontent.com/5275924/187058948-7ce6c684-840e-4331-ab34-56ee1d3ab4cc.jpg)

![BaselineWallet - Frame 8](https://user-images.githubusercontent.com/5275924/187058950-bbca8ab3-ce69-4a9b-ac0c-5789ac1a8de8.jpg)

![BaselineWallet - Frame 9](https://user-images.githubusercontent.com/5275924/187058956-f7cd489c-2fe5-4f03-b455-1fc5a3e5ca35.jpg)

### Passed and documented tests for VC issuance, verification, and presentation generation

**Resolve did** 

Also not required, but useful

![BaselineWallet - Frame 10](https://user-images.githubusercontent.com/5275924/187059012-c733ae1a-ea69-4f3d-b61b-9e83809ba7e9.jpg)

**Issue Credential**

Once issued, the page would move `Verify Credential`.

![BaselineWallet - Frame 11](https://user-images.githubusercontent.com/5275924/187059053-9729d905-e904-4251-b8e0-f5e7984a0470.jpg)

![BaselineWallet - Frame 14](https://user-images.githubusercontent.com/5275924/187059056-2163f1c1-0b5b-4c00-a0a3-8324df364ce3.jpg)

**Verify Credential**

![BaselineWallet - Frame 13](https://user-images.githubusercontent.com/5275924/187059086-24da5447-1ea4-47e3-b697-9da9fa1f8996.jpg)

![BaselineWallet - Frame 15](https://user-images.githubusercontent.com/5275924/187059091-8cddeada-8199-4d9a-8861-720604f2b225.jpg)

![BaselineWallet - Frame 16](https://user-images.githubusercontent.com/5275924/187059095-fa35932e-aa50-4995-ac93-cccda08a363c.jpg)

**Prepare Presentation**

> And effectively manages DIDs and VCs, ideally in a way compliant with the [W3C Universal Wallet](https://w3c-ccg.github.io/universal-wallet-interop-spec/) specification, in a BRI independent way

In this case it seems like having the ability to store credentials that have been issued, and then selected them to be in a presentation. This is another point where the design could be improved because I was trying to use the simplest possible approach. 

![BaselineWallet - Frame 17](https://user-images.githubusercontent.com/5275924/187059189-6140632c-68f8-48ec-81c7-166b6ee7ce12.jpg)

![BaselineWallet - Frame 18](https://user-images.githubusercontent.com/5275924/187059194-825a94a3-e855-4fe2-844b-e21baa2a54ff.jpg)

### Passed and documented tests for sending, receiving, and visually representing in a User Interface 1 protocol token, d. fungible token, and 1 non-fungible token for at least two public blockchains

I tried to design this without duplicating the work that Metamask already provides. This was the part that was too far removed from the Invoice application to try and integrate it, which is why I split of the wallet design. 

**Polygon**

![BaselineWallet - Frame 19](https://user-images.githubusercontent.com/5275924/187059346-70131260-7acc-4214-aeeb-93e6c4c33102.jpg)

![BaselineWallet - Frame 21](https://user-images.githubusercontent.com/5275924/187059350-938b0b26-9d16-48ce-abc4-f7f389e53a38.jpg)

![BaselineWallet - Frame 23](https://user-images.githubusercontent.com/5275924/187059357-05976d15-145e-4e87-aa82-dcf7e6863210.jpg)

![BaselineWallet - Frame 24](https://user-images.githubusercontent.com/5275924/187059359-3a3d72b7-0dfa-4f0c-a498-309468334355.jpg)

**Ethereum**

Same UI as Polygon.

![BaselineWallet - Frame 26](https://user-images.githubusercontent.com/5275924/187059436-ddc3da9a-740e-4636-924c-4e2178837f92.jpg)

![BaselineWallet - Frame 27](https://user-images.githubusercontent.com/5275924/187059441-9ae1775d-0b17-49c7-a3e1-b9c6c5533146.jpg)

![BaselineWallet - Frame 28](https://user-images.githubusercontent.com/5275924/187059448-e9f2ccc8-ad77-44d5-888b-76bb56070037.jpg)

![BaselineWallet - Frame 29](https://user-images.githubusercontent.com/5275924/187059452-b8e9c1ec-1f80-4cd3-80c3-9206ba3d5f4f.jpg)

Looks like I forgot fungible tokens in this design. This part of the RFP on its own is too time consuming for the design and implementation for someone like me who isn't familiar with these things.

### Passed and documented tests for receiving, signing, and sending messages for one BRI

I asked a lot of questions about this, but I'm not 100% clear on it. The way I represented it was to decode and encode a BRI message similar to a JWT. 

![BaselineWallet - Frame 25](https://user-images.githubusercontent.com/5275924/187059588-1633a048-e4ca-42a2-9c44-39be8cb62287.jpg)

**Comment by Therecanbeonlyone1969** [comment]
@wsdOgawa thank you so much! Great start. Currently missing in the design are:
- Update of a DID document (all properties)
- Present a Verifiable Presentation

It might be worthwhile considering to only use Manage DID and then have a selector for a supported DID method (in this case did:key and did:element) that drives in the different modules one for each did method. Similar for VC management. It might be good to have a selector for available VC schemas to be issued. Similarly, if you want, being able to support VC revocation might be nice but not required.

I do not understand though, are you going to submit a grant request for implementing your solution for RFP#1 or not? The former was the ask.

cc @GoldenBit0

**Comment by GoldenBit0** [comment]
@wsdOgawa hello, following up on the comment above

**Comment by mehranshakeri** [comment]
Since it's only the wireframes and budges is $0, then is it really a grant proposal or more of a contribution which should be a PR?

**Comment by wsdOgawa** [comment]
> @wsdOgawa hello, following up on the comment above

Sorry, I wasn't sure how to follow up on @Therecanbeonlyone1969's comment. The original text for RFP #1 was `Passed and documented tests for VC issuance, verification, and presentation generation`. I take the term to `presentation generation` to include the following:

1. create an empty presentation
2. populate presentation with credentials
3. sign presentation

For comparison, when you `generate a mnemonic`, does that include sending that mnemonic over http to another party? I'm not sure where `Present a Verifiable Presentation` is coming.

**Comment by wsdOgawa** [comment]
> Since it's only the wireframes and budges is $0, then is it really a grant proposal or more of a contribution which should be a PR?

The motivation for this issue was to provide a base that could be improved on and added to. For something like sending a presentation, you could include a text field to input a url for where to send the presentation. For updating all properties in a did document, I'm not sure how you would solve that elegantly. Seems like a page that you could design and add as needed.

**Comment by Therecanbeonlyone1969** [comment]
> > Since it's only the wireframes and budges is $0, then is it really a grant proposal or more of a contribution which should be a PR?
> 
> The motivation for this issue was to provide a base that could be improved on and added to. For something like sending a presentation, you could include a text field to input a url for where to send the presentation. For updating all properties in a did document, I'm not sure how you would solve that elegantly. Seems like a page that you could design and add as needed.

@wsdOgawa I am not sure how to respond to your comment. 
- Is this design considered as it currently is to be final? If no will you add what is required based on my comments?
- What is your grant ask for this proposal for RFP#1?
- I presume, if awarded you will submit this work as a standalone code module that can be integrated via an SDK?

**Comment by Therecanbeonlyone1969** [comment]
> For comparison, when you `generate a mnemonic`, does that include sending that mnemonic over http to another party? I'm not sure where `Present a Verifiable Presentation` is coming.

A verifiable presentation (VP) is defined {here}(https://www.w3.org/TR/vc-data-model/#presentations-0) and should be sent via an API. If you want a package that does it for you, you can use e.g. [vc.js](https://github.com/digitalbazaar/vc-js). You can also use the[ vc-http-api ](https://github.com/w3c-ccg/vc-api/)for the API definition for VCs and VPs. Let me know if that does not make sense?

**Comment by GoldenBit0** [comment]
@wsdOgawa I'm going to close this issues due to going stale.

Please reach out when you'd like to continue discussing this work by emailing [baseline-team@oasis-open.org](mailto:baseline-team@oasis-open.org) or via Slack! https://join.slack.com/t/ethereum-baseline/shared_invite/zt-1gu6trxeq-~GO7xe9Z2doeynrUEzaPuw
