### ISSUE TITLE
[GR] Travel Expense reimbursement for fintech_devcon presentation

### ISSUE THREAD

**Issue by mwhaddle** [eea-oasis/baseline-grants#88]
Submitting expense reimbursement form for travel related to fintech_devcon 2022 in Denver, CO

GR] Expense reimbursement for fintech_devcon presentation

Details
In-person presentation titled “Baseline Protocol- Multiparty Data Sharing Under Zero Knowledge” delivered at fintech_devcon 2022 held on August 23-25 in Denver, CO. This is a GR seeking reimbursement for travel/lodging/ground transportation expenses.
Motivation and Overview
Generating mindshare around Baseline Protocol and its applications in the Banking/Financial Services sector. This session was proposed & developed by the Baseline Outreach team for the purposes of the conference as well as creating a slide deck that would be repeatable for subsequent presentations  to different industry verticals.
Value to the Baseline Protocol
The generation of outreach collateral that allows for community members to use in engagements with their respective networks. 
Downsides / Execution Risks / Limitations
None.
Deliverables / Schedule / Milestones
Slide deck completed. Used as the basis to generate additional collateral applicable to different industries & use cases.
Budget
$1000.00
Applicant Background
Marc Haddle has been a regular contributor to Baseline Protocol since May 2020. He currently chairs the Outreach Team.

Conference details- ~1500 attendees. Heavily geared towards applications in Financial Services- payments, secure APIs, Loan underwriting, Platforms (Visa was heavily invested. They seek to encourage project development on their network, with throughput being the most-evangelized feature.) Moov was the overall event sponsor, with heavy emphasis on their product suite around payments.

Outcomes- Baseline was a persistent topic in all social settings, particularly data sharing around zk. It is seen as a lightweight, performant alternative to blockchain projects. The security angle was of particular interest to attendees VGS, Spinwheel, & Basis Theory regarding solutions around data residency and keeping data in respective SORs. Multiparty capability was a universal topic of interest as well. 

[Grant Application.docx](https://github.com/eea-oasis/baseline-grants/files/9619269/Grant.Application.docx)

**Comment by GoldenBit0** [comment]
10/20/22 TSC Meeting Notes:

- The TSC is cautious for reimbursing funds _after_ an event.
- Receipts or a breakdown of the requested reimbursement would help. 
- Outcomes from event (list of new contacts, etc) would help as supporting evidence.

**Comment by mwhaddle** [comment]
This is the first GR of this type, and these requirements for reimbursement have not been clearly communicated. The subject of reimbursement was brought up several times during the preparations for this event. The amount requested is quite small and frankly I am surprised at the notion that this GR not be approved.

**Comment by Therecanbeonlyone1969** [comment]
@mwhaddle in principle, no reimbursement without prior grant request and approval. For approval, if given, the TSC would need the detailed contact list with the contact details of the people you spoke with at the event, and the TSC needs the receipts for the reimbursement request. Thank you! cc @GoldenBit0

**Comment by mwhaddle** [comment]
@Therecanbeonlyone1969 in principle, these requirements should be clearly spelled out for GRs for time & travel for events showcasing Baseline's features & benefits. This way, the grant requestor can easily supply those and not get bogged down in a policy discussion two months after the event. The reimbursement was discussed several times during the content sessions, and no requirements were ever communicated. To my knowledge, this is the first GR of this type...

**Comment by Therecanbeonlyone1969** [comment]
@mwhaddle in principle, all grant requests are for work **to be done**, and once completed, the TSC determines if the requirements and milestones were properly met by the completed work of the requester. That is clearly spelled out last time I checked. There is no need to differentiate between travel and software development or any other type of grant. 

Also, content sessions are not TSC meetings. Only the TSC has the authority to set or change requirements for grant proposals, grant requests, and payouts. Just to be clear. I presume we agree on that.

And as I said above, and as @GoldenBit0 also requested, if you can provide the requested information the TSC will re-consider your request, most likely favorably -- on an exception basis.

**Comment by mwhaddle** [comment]
Very well. Please find the requested items attached. Let me know if you require anything additional.

[Devcon Contact Overview.xlsx](https://github.com/eea-oasis/baseline-grants/files/9882412/Devcon.Contact.Overview.xlsx)
[DevCon Flight Receipt.docx](https://github.com/eea-oasis/baseline-grants/files/9882417/DevCon.Flight.Receipt.docx)
[DevCon Hotel Details.docx](https://github.com/eea-oasis/baseline-grants/files/9882418/DevCon.Hotel.Details.docx)
[Paypal Receipts DevCon.pdf](https://github.com/eea-oasis/baseline-grants/files/9882421/Paypal.Receipts.DevCon.pdf)

**Comment by mwhaddle** [comment]
Here's a Summary...
[DevCon Expense Summary.xlsx](https://github.com/eea-oasis/baseline-grants/files/9882482/DevCon.Expense.Summary.xlsx)

**Comment by Therecanbeonlyone1969** [comment]
good to pay out from my side ... **as an exception this one time** @mwhaddle ... in the future, please, follow the process

**Comment by samratkishor** [comment]
I have changed my vote considering the additional information provided by @mwhaddle upon request and I appreciate the effort and leadership demonstrated. Suggest we follow the process going forward. Cheers!

**Comment by samratkishor** [comment]
I have changed my vote considering the additional information provided by @mwhaddle upon request and I appreciate the effort and leadership demonstrated. Suggest we follow the process going forward. Cheers!

**Comment by GoldenBit0** [comment]
@mwhaddle Approved per majority TSC vote.

Next steps to facilitate payment per the grant process-

1. Submit a PR to add your info to the ['Approved 2022 Grant List'](https://github.com/eea-oasis/baseline-grants/blob/main/Approved-Grants-2022.md)
2. Use the [Grant Payment Request template](https://github.com/eea-oasis/baseline-grants/blob/main/.github/ISSUE_TEMPLATE/grant-payment-request.md) to submit an issue to the Grants Repo.
