### ISSUE TITLE
[Payout Request] Grant Request #84 for Conducting the Baseline Show on a Weekly Basis - Aug & Sept

### ISSUE THREAD

**Issue by samratkishor** [eea-oasis/baseline-grants#91]
**Grant Work Tracker**

https://github.com/eea-oasis/baseline-grants/issues/84

**Links to Final Deliverables**

https://www.youtube.com/c/BaselineProtocol

**Grant Amount**

August - $500, September - $1000, October - $1000, November - $1000, December $1000
Monthly payout

**Requested amount for work (must match approved application)**

Monthly Payout. Total due $1500 at the time of this request.

**Any questions or comments?**
None

**Payment Request Status**
Open

**Comment by GoldenBit0** [comment]
@samratkishor please specify in the title and text that this is for the august/sept payment

**Comment by GoldenBit0** [comment]
Payment approved per majority TSC vote.

**Comment by GoldenBit0** [comment]
Sent to Oasis payments for processing. Keep an eye out from an email from 'OpenCollective' or 'Oasis'

Please reach out to me if you have any issues. 

Closing Issue.
