### ISSUE TITLE
[Payout Request] Completed Baseline Calendar 

### ISSUE THREAD

**Issue by vaibhavgeek** [eea-oasis/baseline-grants#92]
## Baseline Calendar Example 

---

### Grant Application

Grant Application:  https://github.com/eea-oasis/baseline-blips/issues/24

---

### Grant Work Tracker

Pull Request Tracker: https://github.com/eea-oasis/baseline/pull/480
Issue  / Discussion Tracker: https://github.com/eea-oasis/baseline-blips/issues/24

---

### Links to Final Deliverables

Pull Request - https://github.com/eea-oasis/baseline/pull/480 
Demo Video - https://www.youtube.com/watch?v=_eVsyjWFXhw 

---

### Grant Amount

6000$

---

### Notes
Any questions or comments?

---

### Payment Request Status

Payment request is approved if 6 or more TSC members have upvoted (thumbs up) this issue.

**Comment by GoldenBit0** [comment]
@vaibhavgeek The TSC will vote on this once the PR is reviewed/merged.

**Comment by vaibhavgeek** [comment]
@GoldenBit0 I would love to do that! I will share a technical demo video which explains the code/along with the working in frontend.

**Comment by Therecanbeonlyone1969** [comment]
Good to payout, imho ... voted yes above

**Comment by GoldenBit0** [comment]
Per majority TSC vote- grant payment is approved.

**Comment by GoldenBit0** [comment]
Sent to Oasis payments for processing. Keep an eye out from an email from 'OpenCollective' or 'Oasis'

Please reach out to me if you have any issues. 

Closing Issue.
