### ISSUE TITLE
[Payment Request] Travel Expense reinbursement for fintech_devcon August 2022

### ISSUE THREAD

**Issue by mwhaddle** [eea-oasis/baseline-grants#94]
Grant Payment Request
Grant payment request is submitted once the grant project has been completed as specifed in the grant application (or as agreed upon by grant recipient and TSC if there was a scope change).
The payment has been approved if a majority (5 or more) of the [Technical Steering Committee members](https://docs.baseline-protocol.org/governance/technical-steering-committee) upvote this request( thumbs up).
* * *
Grant Title
Travel Expense reinbursement for fintech_devcon August 2022
* * *
Grant Application

https://github.com/eea-oasis/baseline-grants/issues/88
* * *

**Comment by samratkishor** [comment]
Approved with reference to the comments on original request.
