### ISSUE TITLE
Grant Payment Request - Baseline Protocol Website Maintenance (part 1)

### ISSUE THREAD

**Issue by boye** [eea-oasis/baseline-grants#95]
# Grant Payment Request
Grant payment request is submitted once the grant project has been completed as specified in the grant application (or as agreed upon by grant recipient and TSC if there was a scope change). 

The payment has been approved if a majority (6 or more) of the Technical Steering Committee members upvote this request(thumbs up).

## Grant Title
Baseline Protocol Website Maintenance 2022 (part 1)

### Grant Application
Issue #62 

### Grant Work Tracker
https://github.com/eea-oasis/baseline-outreach/issues/19

### Links to Final Deliverables
https://baseline-protocol.org

### Grant Amount
USD $2,500 

### Notes
Part 2 of the website maintenance will be done in 2023

### Payment Request Status
Payment request is approved if 6 or more TSC members have upvoted (thumbs up) this issue.

**Comment by GoldenBit0** [comment]
Boye and I have been in frequent communication during the duration of this grant work. Boye has implemented all requested changes, made additional suggestions to improve the website, and fulfilled grant scope.

Thanks for your help Boye!

**Comment by GoldenBit0** [comment]
Majority TSC approved.
