### ISSUE TITLE
[Payout Request] Conduct the Weekly Office Hours : The Baseline Show #84

### ISSUE THREAD

**Issue by samratkishor** [eea-oasis/baseline-grants#98]
Approved Grant Request: https://github.com/eea-oasis/baseline-grants/issues/84

Shows available on the official YouTube channel: https://www.youtube.com/@BaselineProtocol

Total: $2,750

Request payout for the Months as follows:
1. October 2022- $750 (as one show got canceled)
2. November 2022 - $1000
3. December 2022 - $1000

**Comment by GoldenBit0** [comment]
Edited request to include total value.
